version: '3.8'
services:
  db:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=eden-tech-test
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - eden-tech-test
  www:
    depends_on:
      - db
    container_name: php-apache
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    ports:
      - "80:80"
    networks:
      - eden-tech-test
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8001:80"
    networks:
      - eden-tech-test
volumes:
  db:
    driver: local
networks:
  eden-tech-test:
    driver: bridge